INSERT INTO USERS(NAME,CITY,STATE,CODE,PEANUT_ALLERGY,EGG_ALLERGY,DAIRY_ALLERGY)
VALUES ('JonnyCage','New York','NY',10001,true,true,true);
INSERT INTO USERS(NAME,CITY,STATE,CODE,PEANUT_ALLERGY,EGG_ALLERGY,DAIRY_ALLERGY)
VALUES ('JonLee','Paris','France',80001,true,null,true);

INSERT INTO REVIEWS(USERNAME,RESTAURANTID,PEANUT_SCORE,EGG_SCORE,DAIRY_SCORE,COMMENT, STATUS)
VALUES ('JonnyCage',1,2,4,3,'Delicious food!!!', 'p');

INSERT INTO RESTAURANTS(NAME,CITY,STATE,ZIPCODE,PEANUT_AVG_SCORE,EGG_AVG_SCORE,DAIRY_AVG_SCORE,AVG_SCORE)
VALUES ('My Favorite Pizza Place','Iasi','Romania',700500,null,null,null,null);

INSERT INTO ADMINS(NAME)
VALUES('AdminOne');
INSERT INTO ADMINS(NAME)
VALUES('AdminTwo');

INSERT INTO ADMIN_REVIEWS(ADMIN_ID, REVIEW_ID, REVIEW_STATUS)
VALUES (1,1,'p')