INSERT INTO USERS(NAME,CITY,STATE,CODE,PEANUT_ALLERGY,EGG_ALLERGY,DAIRY_ALLERGY)
VALUES ('JonnyCage','New York','NY',10001,true,true,true);
INSERT INTO USERS(NAME,CITY,STATE,CODE,PEANUT_ALLERGY,EGG_ALLERGY,DAIRY_ALLERGY)
VALUES ('JonLee','Paris','France',80001,true,null,true);