INSERT INTO USERS(NAME,CITY,STATE,CODE,PEANUT_ALLERGY,EGG_ALLERGY,DAIRY_ALLERGY)
VALUES ('LidiaPoe','New York','NY',70801,true,true,true);
INSERT INTO USERS(NAME,CITY,STATE,CODE,PEANUT_ALLERGY,EGG_ALLERGY,DAIRY_ALLERGY)
VALUES ('JonLee','Paris','France',80001,true,null,true);

INSERT INTO REVIEWS(USERNAME,RESTAURANTID,PEANUT_SCORE,EGG_SCORE,DAIRY_SCORE,COMMENT, STATUS)
VALUES ('LidiaPoe',1,2,4,3,'Delicious food!', 'p');
INSERT INTO REVIEWS(USERNAME,RESTAURANTID,PEANUT_SCORE,EGG_SCORE,DAIRY_SCORE,COMMENT, STATUS)
VALUES ('JonLee',2,null,null,5,'Best bubble tea!', 'p');
INSERT INTO REVIEWS(USERNAME,RESTAURANTID,PEANUT_SCORE,EGG_SCORE,DAIRY_SCORE,COMMENT, STATUS)
VALUES ('LidiaPoe',2,2,null,3,'Not a fan of the bursting bubbles', 'p');

INSERT INTO RESTAURANTS(NAME,CITY,STATE,ZIPCODE,PEANUT_AVG_SCORE,EGG_AVG_SCORE,DAIRY_AVG_SCORE,AVG_SCORE)
VALUES ('My Favorite Pizza Place','Iasi','Romania','700500',null,2,null,2);
INSERT INTO RESTAURANTS(NAME,CITY,STATE,ZIPCODE,PEANUT_AVG_SCORE,EGG_AVG_SCORE,DAIRY_AVG_SCORE,AVG_SCORE)
VALUES ('Bubble Tea Joy','Tokyo','Japan','100-0102',null,null,null,null);

INSERT INTO ADMINS(NAME)
VALUES('AdminOne');
INSERT INTO ADMINS(NAME)
VALUES('AdminTwo');

INSERT INTO ADMIN_REVIEWS(ADMIN_ID, REVIEW_ID, REVIEW_STATUS)
VALUES (1,1,'p')